[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "openai>=2.5.0",
    "pandas>=2.3.3",
    "requests>=2.32.5",
    "supabase>=2.22.0",
]
